unsigned char Map[360];
unsigned int GameScreenStart[] = {0, 0};

Texture2D MainMenuTile;
Texture2D MainMenuDoor;
Texture2D MainMenuKey;
Texture2D tile0;
Texture2D tile1;
Texture2D tile2;
Texture2D tile3;
Texture2D tile4;
Texture2D tile5;
Texture2D PlayerTile;
Texture2D PlayerTile1;
Texture2D PlayerTile2;
Texture2D PlayerTile3;
Texture2D PlayerTile4;
Texture2D PlayerTile5;
Texture2D PlayerTile6;
Texture2D PlayerTile7;
Texture2D PlayerTile8;
Texture2D PlayerTile9;
Texture2D PlayerTile10;
Texture2D PlayerTile11;
Texture2D PlayerTile12;
Texture2D tile18;
Texture2D tile19;
Texture2D tile20;
Texture2D tile21;
Texture2D tile22;
Texture2D tile23;
Texture2D tile24;
Texture2D tile25;
Texture2D tile26;
Texture2D tile27;
Texture2D tile28;
Texture2D tile29;
Texture2D tile30;
Texture2D tile31;
Texture2D tile32;
Texture2D tile33;
Texture2D tile34;
Texture2D tile35;
Texture2D tile36;
Texture2D tile37;
Texture2D tile38;
Texture2D tile39;
Texture2D tile40;
Texture2D tile41;
Texture2D tile42;
Texture2D tile43;
Texture2D tile44;
Texture2D tile45;
Texture2D tile46;
Texture2D tile47;
Texture2D tile48;
Texture2D tile49;
Texture2D tile50;
Texture2D tile51;
Texture2D tile52;
Texture2D tile53;
Texture2D tile54;
Texture2D tile55;
Texture2D tile56;
Texture2D tile57;
Texture2D tile58;
Texture2D tile59;
Texture2D tile60;
Texture2D tile61;
Texture2D tile62;
Texture2D tile63;
Texture2D tile64;
Texture2D tile65;
Texture2D tile66;
Texture2D tile67;
Texture2D tile68;
Texture2D tile69;
Texture2D tile70;
Texture2D TileSet;

static void intTextures(){
    MainMenuTile = LoadTexture("resources/Graphics/MainMenu/MainMenu.png"); 
    MainMenuDoor = LoadTexture("resources/Graphics/MainMenu/MainMenuDoorClosed.png"); 
    MainMenuKey = LoadTexture("resources/Graphics/MainMenu/MainMenuKey.png"); 
    tile0 = LoadTexture("resources/Graphics/Misc/Tile00.png"); 
    tile1 = LoadTexture("resources/Graphics/Misc/Tile01.png"); 
	tile2 = LoadTexture("resources/Graphics/Wall/Tile02.png"); 
    tile3 = LoadTexture("resources/Graphics/Misc/Tile03.png"); 
    tile4 = LoadTexture("resources/Graphics/Misc/Tile04.png"); 
    tile5 = LoadTexture("resources/Graphics/Misc/Tile05.png"); 
    PlayerTile = LoadTexture("resources/Graphics/Player/Tile06.png");
    PlayerTile1 = LoadTexture("resources/Graphics/Player/Tile06.png");
    PlayerTile2 = LoadTexture("resources/Graphics/Player/Tile07.png");
    PlayerTile3 = LoadTexture("resources/Graphics/Player/Tile08.png");
    PlayerTile4 = LoadTexture("resources/Graphics/Player/Tile09.png");
    PlayerTile5 = LoadTexture("resources/Graphics/Player/Tile010.png");
    PlayerTile6 = LoadTexture("resources/Graphics/Player/Tile011.png");
    PlayerTile7 = LoadTexture("resources/Graphics/Player/Tile012.png");
    PlayerTile8 = LoadTexture("resources/Graphics/Player/Tile013.png");
    PlayerTile9 = LoadTexture("resources/Graphics/Player/Tile014.png");
    PlayerTile10 = LoadTexture("resources/Graphics/Player/Tile015.png");
    PlayerTile11 = LoadTexture("resources/Graphics/Player/Tile016.png");
    PlayerTile12 = LoadTexture("resources/Graphics/Player/Tile017.png");
    tile18 = LoadTexture("resources/Graphics/Misc/Tile018.png");
    tile19 = LoadTexture("resources/Graphics/Misc/Tile019.png");
    tile20 = LoadTexture("resources/Graphics/Misc/Tile020.png");
    tile21 = LoadTexture("resources/Graphics/Misc/Tile021.png");
    tile22 = LoadTexture("resources/Graphics/Misc/Tile022.png");
    tile23 = LoadTexture("resources/Graphics/Enime/Tile023.png");
    tile24 = LoadTexture("resources/Graphics/Enime/Tile024.png");
    tile25 = LoadTexture("resources/Graphics/Enime/Tile025.png");
    tile26 = LoadTexture("resources/Graphics/Enime/Tile026.png");
	tile27 = LoadTexture("resources/Graphics/Wall/Tile027.png");
    tile28 = LoadTexture("resources/Graphics/Wall/Tile028.png");
    tile29 = LoadTexture("resources/Graphics/Wall/Tile029.png");
    tile30 = LoadTexture("resources/Graphics/Wall/Tile030.png");
    tile31 = LoadTexture("resources/Graphics/Wall/Tile031.png");
    tile32 = LoadTexture("resources/Graphics/Wall/Tile032.png");
    tile33 = LoadTexture("resources/Graphics/Wall/Tile033.png");
    tile34 = LoadTexture("resources/Graphics/Wall/Tile034.png");
    tile35 = LoadTexture("resources/Graphics/Wall/Tile035.png");
    tile36 = LoadTexture("resources/Graphics/Wall/Tile036.png");
    tile37 = LoadTexture("resources/Graphics/Wall/Tile037.png");
    tile38 = LoadTexture("resources/Graphics/Wall/Tile038.png");
    tile39 = LoadTexture("resources/Graphics/Wall/Tile039.png");
    tile40 = LoadTexture("resources/Graphics/Wall/Tile040.png");
    tile41 = LoadTexture("resources/Graphics/Wall/Tile041.png");
    tile42 = LoadTexture("resources/Graphics/Wall/Tile042.png");
    tile43 = LoadTexture("resources/Graphics/Wall/Tile043.png");
    tile44 = LoadTexture("resources/Graphics/Wall/Tile044.png");
    tile45 = LoadTexture("resources/Graphics/Wall/Tile045.png");
    tile46 = LoadTexture("resources/Graphics/Wall/Tile046.png");
    tile47 = LoadTexture("resources/Graphics/Wall/Tile047.png");
    tile48 = LoadTexture("resources/Graphics/Wall/Tile048.png");
    tile49 = LoadTexture("resources/Graphics/Wall/Tile049.png");
    tile50 = LoadTexture("resources/Graphics/Wall/Tile050.png");
    tile51 = LoadTexture("resources/Graphics/Wall/Tile051.png");
    tile52 = LoadTexture("resources/Graphics/Wall/Tile052.png");
    tile53 = LoadTexture("resources/Graphics/Wall/Tile053.png");
    tile54 = LoadTexture("resources/Graphics/Wall/Tile054.png");
    tile55 = LoadTexture("resources/Graphics/Wall/Tile055.png");
    tile56 = LoadTexture("resources/Graphics/Wall/Tile056.png");
    tile57 = LoadTexture("resources/Graphics/Wall/Tile057.png");
    tile58 = LoadTexture("resources/Graphics/Wall/Tile058.png");
    tile59 = LoadTexture("resources/Graphics/Wall/Tile059.png");
    tile60 = LoadTexture("resources/Graphics/Wall/Tile060.png");
    tile61 = LoadTexture("resources/Graphics/Wall/Tile061.png");
    tile62 = LoadTexture("resources/Graphics/Wall/Tile062.png");
    tile63 = LoadTexture("resources/Graphics/Wall/Tile063.png");
	tile64 = LoadTexture("resources/Graphics/Wall/Tile064.png");
	tile65 = LoadTexture("resources/Graphics/Wall/Tile065.png");
	tile66 = LoadTexture("resources/Graphics/Wall/Tile066.png");
    tile67 = LoadTexture("resources/Graphics/Wall/Tile067.png");
    tile68 = LoadTexture("resources/Graphics/Wall/Tile068.png");
    tile69 = LoadTexture("resources/Graphics/Wall/Tile069.png");
    tile70 = LoadTexture("resources/Graphics/Wall/Tile70.png");
	TileSet = LoadTexture("resources/Tileset.png");
}

static void DrawBKG(){
    ClearBackground(BLACK);
    DrawTexture(tile0, GameScreenStart[0], GameScreenStart[1], WHITE);
	for(int i = 0; i < 20; i++){
        for(int j = 0; j < 18; j++){
            switch(Map[(j*20)+(i)]){
                case 0x01:DrawTexture(tile1, (i * 40) + GameScreenStart[0], (j * 40) + GameScreenStart[1], WHITE);break;
				case 0x02:DrawTexture(tile2, (i * 40) + GameScreenStart[0], (j * 40) + GameScreenStart[1], WHITE);break;
                case 0x03:DrawTexture(tile3, (i * 40) + GameScreenStart[0], (j * 40) + GameScreenStart[1], WHITE);break;
                case 0x04:DrawTexture(tile4, (i * 40) + GameScreenStart[0], (j * 40) + GameScreenStart[1], WHITE);break;
                case 0x05:DrawTexture(tile5, (i * 40) + GameScreenStart[0], (j * 40) + GameScreenStart[1], WHITE);break;
                case 0x12:DrawTexture(tile18, (i * 40) + GameScreenStart[0], (j * 40) + GameScreenStart[1], WHITE);break;
                case 0x13:DrawTexture(tile19, (i * 40) + GameScreenStart[0], (j * 40) + GameScreenStart[1], WHITE);break;
                case 0x14:DrawTexture(tile20, (i * 40) + GameScreenStart[0], (j * 40) + GameScreenStart[1], WHITE);break;
                case 0x15:DrawTexture(tile21, (i * 40) + GameScreenStart[0], (j * 40) + GameScreenStart[1], WHITE);break;
                case 0x16:DrawTexture(tile22, (i * 40) + GameScreenStart[0], (j * 40) + GameScreenStart[1], WHITE);break;
                case 0x17:DrawTexture(tile23, (i * 40) + GameScreenStart[0], (j * 40) + GameScreenStart[1], WHITE);break;
                case 0x18:DrawTexture(tile24, (i * 40) + GameScreenStart[0], (j * 40) + GameScreenStart[1], WHITE);break;
                case 0x19:DrawTexture(tile25, (i * 40) + GameScreenStart[0], (j * 40) + GameScreenStart[1], WHITE);break;
                case 0x1A:DrawTexture(tile26, (i * 40) + GameScreenStart[0], (j * 40) + GameScreenStart[1], WHITE);break;
				case 0x1B:DrawTexture(tile27, (i * 40) + GameScreenStart[0], (j * 40) + GameScreenStart[1], WHITE);break;
                case 0x1C:DrawTexture(tile28, (i * 40) + GameScreenStart[0], (j * 40) + GameScreenStart[1], WHITE);break;
                case 0x1D:DrawTexture(tile29, (i * 40) + GameScreenStart[0], (j * 40) + GameScreenStart[1], WHITE);break;
                case 0x1E:DrawTexture(tile30, (i * 40) + GameScreenStart[0], (j * 40) + GameScreenStart[1], WHITE);break;
                case 0x1F:DrawTexture(tile31, (i * 40) + GameScreenStart[0], (j * 40) + GameScreenStart[1], WHITE);break;
                case 0x20:DrawTexture(tile32, (i * 40) + GameScreenStart[0], (j * 40) + GameScreenStart[1], WHITE);break;
                case 0x21:DrawTexture(tile33, (i * 40) + GameScreenStart[0], (j * 40) + GameScreenStart[1], WHITE);break;
                case 0x22:DrawTexture(tile34, (i * 40) + GameScreenStart[0], (j * 40) + GameScreenStart[1], WHITE);break;
                case 0x23:DrawTexture(tile35, (i * 40) + GameScreenStart[0], (j * 40) + GameScreenStart[1], WHITE);break;
                case 0x24:DrawTexture(tile36, (i * 40) + GameScreenStart[0], (j * 40) + GameScreenStart[1], WHITE);break;
                case 0x25:DrawTexture(tile37, (i * 40) + GameScreenStart[0], (j * 40) + GameScreenStart[1], WHITE);break;
                case 0x26:DrawTexture(tile38, (i * 40) + GameScreenStart[0], (j * 40) + GameScreenStart[1], WHITE);break;
                case 0x27:DrawTexture(tile39, (i * 40) + GameScreenStart[0], (j * 40) + GameScreenStart[1], WHITE);break;
                case 0x28:DrawTexture(tile40, (i * 40) + GameScreenStart[0], (j * 40) + GameScreenStart[1], WHITE);break;
                case 0x29:DrawTexture(tile41, (i * 40) + GameScreenStart[0], (j * 40) + GameScreenStart[1], WHITE);break;
                case 0x2A:DrawTexture(tile42, (i * 40) + GameScreenStart[0], (j * 40) + GameScreenStart[1], WHITE);break;
                case 0x2B:DrawTexture(tile43, (i * 40) + GameScreenStart[0], (j * 40) + GameScreenStart[1], WHITE);break;
                case 0x2C:DrawTexture(tile44, (i * 40) + GameScreenStart[0], (j * 40) + GameScreenStart[1], WHITE);break;
                case 0x2D:DrawTexture(tile45, (i * 40) + GameScreenStart[0], (j * 40) + GameScreenStart[1], WHITE);break;
                case 0x2E:DrawTexture(tile46, (i * 40) + GameScreenStart[0], (j * 40) + GameScreenStart[1], WHITE);break;
                case 0x2F:DrawTexture(tile47, (i * 40) + GameScreenStart[0], (j * 40) + GameScreenStart[1], WHITE);break;
                case 0x30:DrawTexture(tile48, (i * 40) + GameScreenStart[0], (j * 40) + GameScreenStart[1], WHITE);break;
                case 0x31:DrawTexture(tile49, (i * 40) + GameScreenStart[0], (j * 40) + GameScreenStart[1], WHITE);break;
                case 0x32:DrawTexture(tile50, (i * 40) + GameScreenStart[0], (j * 40) + GameScreenStart[1], WHITE);break;
                case 0x33:DrawTexture(tile51, (i * 40) + GameScreenStart[0], (j * 40) + GameScreenStart[1], WHITE);break;
                case 0x34:DrawTexture(tile52, (i * 40) + GameScreenStart[0], (j * 40) + GameScreenStart[1], WHITE);break;
                case 0x35:DrawTexture(tile53, (i * 40) + GameScreenStart[0], (j * 40) + GameScreenStart[1], WHITE);break;
                case 0x36:DrawTexture(tile54, (i * 40) + GameScreenStart[0], (j * 40) + GameScreenStart[1], WHITE);break;
                case 0x37:DrawTexture(tile55, (i * 40) + GameScreenStart[0], (j * 40) + GameScreenStart[1], WHITE);break;
                case 0x38:DrawTexture(tile56, (i * 40) + GameScreenStart[0], (j * 40) + GameScreenStart[1], WHITE);break;
                case 0x39:DrawTexture(tile57, (i * 40) + GameScreenStart[0], (j * 40) + GameScreenStart[1], WHITE);break;
                case 0x3A:DrawTexture(tile58, (i * 40) + GameScreenStart[0], (j * 40) + GameScreenStart[1], WHITE);break;
                case 0x3B:DrawTexture(tile59, (i * 40) + GameScreenStart[0], (j * 40) + GameScreenStart[1], WHITE);break;
                case 0x3C:DrawTexture(tile60, (i * 40) + GameScreenStart[0], (j * 40) + GameScreenStart[1], WHITE);break;
                case 0x3D:DrawTexture(tile61, (i * 40) + GameScreenStart[0], (j * 40) + GameScreenStart[1], WHITE);break;
                case 0x3E:DrawTexture(tile62, (i * 40) + GameScreenStart[0], (j * 40) + GameScreenStart[1], WHITE);break;
                case 0x3F:DrawTexture(tile63, (i * 40) + GameScreenStart[0], (j * 40) + GameScreenStart[1], WHITE);break;
				case 0x40:DrawTexture(tile64, (i * 40) + GameScreenStart[0], (j * 40) + GameScreenStart[1], WHITE);break;
				case 0x41:DrawTexture(tile65, (i * 40) + GameScreenStart[0], (j * 40) + GameScreenStart[1], WHITE);break;
				case 0x42:DrawTexture(tile66, (i * 40) + GameScreenStart[0], (j * 40) + GameScreenStart[1], WHITE);break;
                case 0x43:DrawTexture(tile67, (i * 40) + GameScreenStart[0], (j * 40) + GameScreenStart[1], WHITE);break;
                case 0x44:DrawTexture(tile68, (i * 40) + GameScreenStart[0], (j * 40) + GameScreenStart[1], WHITE);break;
                case 0x45:DrawTexture(tile69, (i * 40) + GameScreenStart[0], (j * 40) + GameScreenStart[1], WHITE);break;
                case 0x46:DrawTexture(tile70, (i * 40) + GameScreenStart[0], (j * 40) + GameScreenStart[1], WHITE);break;
			}
        }
    }
}

static void UnloadTextures(){
    UnloadTexture(MainMenuTile); 
    UnloadTexture(MainMenuDoor); 
    UnloadTexture(MainMenuKey); 
    UnloadTexture(PlayerTile1);
    UnloadTexture(PlayerTile2);
    UnloadTexture(PlayerTile3);
    UnloadTexture(PlayerTile4);
    UnloadTexture(PlayerTile5);
    UnloadTexture(PlayerTile6);
    UnloadTexture(PlayerTile7);
    UnloadTexture(PlayerTile8);
    UnloadTexture(PlayerTile9);
    UnloadTexture(PlayerTile10);
    UnloadTexture(PlayerTile11);
    UnloadTexture(PlayerTile12);
    UnloadTexture(PlayerTile);
    UnloadTexture(tile1);
    UnloadTexture(tile2);
    UnloadTexture(tile3);
    UnloadTexture(tile4);
    UnloadTexture(tile5);
    UnloadTexture(tile18);
    UnloadTexture(tile19);
    UnloadTexture(tile20); 
    UnloadTexture(tile21);
    UnloadTexture(tile22);
    UnloadTexture(tile23);
    UnloadTexture(tile24);
    UnloadTexture(tile25);
    UnloadTexture(tile26);
    UnloadTexture(tile27);
    UnloadTexture(tile28);
    UnloadTexture(tile29);
    UnloadTexture(tile30); 
    UnloadTexture(tile31);
    UnloadTexture(tile32);
    UnloadTexture(tile33);
    UnloadTexture(tile34);
    UnloadTexture(tile35);
    UnloadTexture(tile36);
    UnloadTexture(tile37);
    UnloadTexture(tile38);
    UnloadTexture(tile39);
    UnloadTexture(tile40); 
    UnloadTexture(tile41);
    UnloadTexture(tile42);
    UnloadTexture(tile43);
    UnloadTexture(tile44);
    UnloadTexture(tile45);
    UnloadTexture(tile46);
    UnloadTexture(tile47);
    UnloadTexture(tile48);
    UnloadTexture(tile49);
    UnloadTexture(tile50); 
    UnloadTexture(tile51);
    UnloadTexture(tile52);
    UnloadTexture(tile53);
    UnloadTexture(tile54);
    UnloadTexture(tile55);
    UnloadTexture(tile56);
    UnloadTexture(tile57);
    UnloadTexture(tile58);
    UnloadTexture(tile59);
    UnloadTexture(tile60);
    UnloadTexture(tile61);
    UnloadTexture(tile62);
    UnloadTexture(tile63);
    UnloadTexture(tile64);
    UnloadTexture(tile65);
    UnloadTexture(tile66);
    UnloadTexture(tile67);
    UnloadTexture(tile68);
    UnloadTexture(tile69);
    UnloadTexture(tile70);
	CloseWindow();
}